### ISSUE TITLE
Listing old games (works in browser)

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-tictactoe-rails-api#6]
Ok, this all started with the following error. I pushed a commit at the spot where I encountered the issue. It should be the first commit (called `errors on list prev games`): https://github.com/onyoo/js-tictactoe-rails-api-v-000

```
#integration tests of persistence if i click the previous game button and a game has already been saved it should add the previous game to the DOM
Expected 0 to be 1.
Error: Expected 0 to be 1.
    at stack (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1293:17)
    at buildExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:484:18)
    at Spec.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:260:46)
    at Expectation.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:442:21)
    at Expectation.toBe (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1209:12)
    at file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:323:45
    at MockAjax.withMock (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/lib/mock-ajax.js:499:17)
    at Object.<anonymous> (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:308:18)
    at attemptSync (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1510:12)
```

The problem is that when I play and save games in the browser, I can list them with no problem:
<img width="184" alt="screen shot 2016-03-04 at 12 16 59 am" src="https://cloud.githubusercontent.com/assets/14326883/13513508/a48bf90c-e1a1-11e5-84ca-7c3ba1c5a760.png">

After a bit of poking around, I put a debugger in the test and found that the request for a game was coming back correctly (debugger put at line tictactoe.spec.js:322):
```
response
Object {status: 200, contentType: "application/json", responseText: "{"games":[{"id":1,"state":["X","","","","","","","",""]}]}"}
```
They are simply not loading correctly. At that same debugger break-point, the dom is visibly missing an empty space for the list div. I checked to see the setFixtures() parameters in the test, and they were indeed missing the ul.

Fix:
Add `<ul id="list"></ul>` to the `#games` div, or just replace line 305 with:
```
    setFixtures('<body><table border="1" cellpadding="40"><tr><td data-x="0", data-y="0">X</td><td data-x="1", data-y="0"></td><td data-x="2", data-y="0"></td></tr><tr><td data-x="0", data-y="1">O</td><td data-x="1", data-y="1"></td><td data-x="2", data-y="1"></td></tr><tr><td data-x="0", data-y="2"></td><td data-x="1", data-y="2"></td><td data-x="2", data-y="2"></td></tr></table><div id="games"><ul id="list"></ul></div><div id="message"></div><button id="save">Save Game</button><button id="previous">Show Previous Games</button></body>');

```

But now that the div has a permanent child, we just created a new problem with line 307:
```
#integration tests of persistence if i click the previous game button and a game has already been saved it should add the previous game to the DOM
Expected 1 to be 0.
Error: Expected 1 to be 0.
    at stack (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1293:17)
    at buildExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:484:18)
    at Spec.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:260:46)
    at Expectation.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:442:21)
    at Expectation.toBe (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1209:12)
    at Object.<anonymous> (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:307:43)
    at attemptSync (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1510:12)
    at QueueRunner.run (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1498:9)
    at QueueRunner.execute (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1485:10)
```
Fix:
Change line 307: `expect($("#games").children().length).toBe(0);` to `expect($("#list").children().length).toBe(0);`

Change line 322: `expect($("#games").children().length).toBe(1);` to `expect($("#list").children().length).toBe(1);`

That is, assuming the ul originally has an id = list. I can't remember if I added that attribute.

**Comment by onyoo** [comment]
Same issue line 329, 344, 364, 371,  and 391.

**Comment by onyoo** [comment]
setFixtures() on line 369 should not be pre-populated ( like the one above). This blank board works:
```
    setFixtures('<body><table border="1" cellpadding="40"><tr><td data-x="0", data-y="0"></td><td data-x="1", data-y="0"></td><td data-x="2", data-y="0"></td></tr><tr><td data-x="0", data-y="1"></td><td data-x="1", data-y="1"></td><td data-x="2", data-y="1"></td></tr><tr><td data-x="0", data-y="2"></td><td data-x="1", data-y="2"></td><td data-x="2", data-y="2"></td></tr></table><div id="games"><ul id="list"></ul></div><div id="message"></div><button id="save">Save Game</button><button id="previous">Show Previous Games</button></body>');
```

**Comment by PeterBell** [comment]
Hey @aturkewi mind having a look at this and seeing if it's related to the issue you raised or any of the issues you've seen with this lab?

**Comment by aturkewi** [comment]
Hey @onyoo thanks for this detailed issue report.

First off, with regards to changing how the test looks for previous games. I think we're actually going to leave it as it is. One way to solve this as it is by doing the following:
```
<ul>
  <div id="games">
    <li data-gameid="1">1</li>
    <li data-gameid="2">2</li>
  </div>
</ul>
```
Where we have the div with the id 'game _inside_ the 'ul' tag. 

As for having some X and O pre-set in the fixtures, those were removed in PR #13 

Thanks again!

**Comment by onyoo** [comment]
Thanks for the follow-up @aturkewi ! Glad to hear it was fixed, and working now!
