### ISSUE TITLE
tictactoe.spec.rb:458 test game not loading

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-tictactoe-rails-api#8]
I'm not sure what the problem is on this one. I submitted with the test lines 459-462 commented out.

The problem is that when clicking on the the right saved game, the game doesn't load. When I run the app in the browser, everything works fine, though. When I put a debugger in loadGame() it never runs. I can't seem to find what's going wrong. 

https://github.com/onyoo/js-tictactoe-rails-api-v-000

<img width="1212" alt="screen shot 2016-03-04 at 2 40 16 am" src="https://cloud.githubusercontent.com/assets/14326883/13515545/90c11752-e1b2-11e5-97a7-003e6b906963.png">

Errors:
```
#integration tests of persistence if should be able to switch to an old game
Expected 'X' to be ''.
Error: Expected 'X' to be ''.
    at stack (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1293:17)
    at buildExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:484:18)
    at Spec.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:260:46)
    at Expectation.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:442:21)
    at Expectation.toBe (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1209:12)
    at file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:459:52
    at MockAjax.withMock (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/lib/mock-ajax.js:499:17)
    at Object.<anonymous> (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:436:18)
    at attemptSync (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1510:12)
Expected '' to be 'X'.
Error: Expected '' to be 'X'.
    at stack (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1293:17)
    at buildExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:484:18)
    at Spec.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:260:46)
    at Expectation.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:442:21)
    at Expectation.toBe (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1209:12)
    at file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:460:52
    at MockAjax.withMock (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/lib/mock-ajax.js:499:17)
    at Object.<anonymous> (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:436:18)
    at attemptSync (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1510:12)
Expected '' to be 'O'.
Error: Expected '' to be 'O'.
    at stack (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1293:17)
    at buildExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:484:18)
    at Spec.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:260:46)
    at Expectation.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:442:21)
    at Expectation.toBe (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1209:12)
    at file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:461:52
    at MockAjax.withMock (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/lib/mock-ajax.js:499:17)
    at Object.<anonymous> (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:436:18)
    at attemptSync (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1510:12)
Expected '' to be 'O'.
Error: Expected '' to be 'O'.
    at stack (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1293:17)
    at buildExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1270:14)
    at Spec.Env.expectationResultFactory (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:484:18)
    at Spec.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:260:46)
    at Expectation.addExpectationResult (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:442:21)
    at Expectation.toBe (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1209:12)
    at file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:462:52
    at MockAjax.withMock (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/lib/mock-ajax.js:499:17)
    at Object.<anonymous> (file:///Users/Roberto/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:436:18)
    at attemptSync (file:///Users/Roberto/.rvm/gems/ruby-2.2.3/gems/learn-test-1.2.26/lib/learn_test/jasmine/jasmine.js:1510:12)
```

**Comment by pletcher** [comment]
It looks like (from the console output) you're running into CORS errors with the tests. Without knowing too much about this lab, it seems like something can't be right with how saved games are being loaded.

My sense is that these tests will need to be revisited, but we might have to icebox it for the time being. Thanks for reporting this.
