### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by ShanaLMoore** [learn-co-curriculum/js-tictactoe-rails-api#9]
I'm trying to  build out this lab by following the tests. When I run the learn command, it runs the controller tests which I've passed. Now I want to access the tictactoe spec,  but receive this error: 

Shana: js-tictactoe-rails-api-v-000
♥ rspec spec/tictactoe.spec.js 
/Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load': /Users/Shana/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:14: `$(' is not allowed as a global variable name (SyntaxError)
/Users/Shana/Development/code/js-tictactoe-rails-api-v-000/spec/tictactoe.spec.js:14: syntax error, unexpected end-of-input, expecting '}'
      $(selector).click();
       ^
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/Shana/.rvm/gems/ruby-2.2.1/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/Shana/.rbenv/versions/2.2.2/bin/rspec:23:in `load'
	from /Users/Shana/.rbenv/versions/2.2.2/bin/rspec:23:in `<main>'

**Comment by ShanaLMoore** [comment]
I got the tests to load using the sudo learn command.
